<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>64d75267-e27c-4e0b-aa99-2705f7ee16be</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Extreme" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
